-- MySQL Script generated by MySQL Workbench
-- Fri Jan 27 18:04:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_agro_delas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_agro_delas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_agro_delas` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_agro_delas` ;

-- -----------------------------------------------------
-- Table `db_agro_delas`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_agro_delas`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_agro_delas`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_agro_delas`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(14) NULL,
  `cnpj` VARCHAR(18) NULL,
  `email` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo_usuario` INT NOT NULL,
  `numero` INT NOT NULL,
  `cep` INT NOT NULL,
  `celular` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_agro_delas`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_agro_delas`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_agro_delas`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_agro_delas`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `peso` DECIMAL(3,2) NULL,
  `volume` INT NULL,
  `quantidade` INT NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  `categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_agro_delas`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `db_agro_delas`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
